/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "surface": "#f8f9fb",
        "secondary-fixed-dim": "#b7c7e8",
        "primary-fixed": "#dae2ff",
        "secondary-container": "#cdddff",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-container": "#51617e",
        "tertiary-fixed": "#afecff",
        "on-background": "#191c1e",
        "error": "#FF5630",
        "inverse-on-surface": "#f0f1f3",
        "surface-dim": "#d9dadc",
        "on-surface-variant": "#434654",
        "surface-container-high": "#e7e8ea",
        "background": "#f8f9fb",
        "primary-container": "#0052cc",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#374763",
        "on-primary-fixed-variant": "#0040a2",
        "secondary-fixed": "#d6e3ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#091c35",
        "outline-variant": "#c3c6d6",
        "on-error": "#ffffff",
        "tertiary": "#004b59",
        "on-primary-fixed": "#001848",
        "error-container": "#ffdad6",
        "outline": "#737685",
        "success": "#36B37E",
        "secondary": "#4f5f7b",
        "inverse-primary": "#b2c5ff",
        "surface-variant": "#e1e2e4",
        "border-subtle": "#DFE1E6",
        "row-hover": "#DEEBFF",
        "primary": "#0052CC",
        "on-primary-container": "#c4d2ff",
        "surface-bright": "#f8f9fb",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001f27",
        "on-tertiary-fixed-variant": "#004e5d",
        "tertiary-fixed-dim": "#48d7f9",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-container": "#76e2ff",
        "surface-container": "#edeef0",
        "surface-white": "#FFFFFF",
        "on-primary": "#ffffff",
        "tertiary-container": "#006477",
        "surface-tint": "#0c56d0",
        "surface-container-highest": "#e1e2e4",
        "warning": "#FFAB00"
      },
      borderRadius: {
        "DEFAULT": "4px",
        "lg": "8px",
        "xl": "12px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "gutter": "16px",
        "xs": "4px",
        "lg": "24px",
        "xl": "32px",
        "base": "4px",
        "sidebar-width": "240px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }]
      },
      maxWidth: {
        "container-max": "1440px"
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
