import { useState, useEffect, useRef } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { useAuth } from '@/hooks/useAuth'
import { authService } from '@/api/services/auth'
import { useAuthStore } from '@/store/authStore'
import { getRolesFromToken } from '@/lib/token'
import { getDefaultRoute } from '@/lib/roles'

export function MfaVerificationPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const method = searchParams.get('method') || 'authenticator'
  const { clearAuth } = useAuth()

  const [digits, setDigits] = useState<string[]>(Array(6).fill(''))
  const [timer, setTimer] = useState(30)
  const [error, setError] = useState(false)
  const [loading, setLoading] = useState(false)
  const [timerExpired, setTimerExpired] = useState(false)
  const [qrCode, setQrCode] = useState('')
  const [secret, setSecret] = useState('')

  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  // Method details mapping
  const methodTitle = {
    authenticator: 'Authenticator App',
    sms: 'SMS Verification',
    email: 'Email Code'
  }[method] || 'Two-Step Verification'

  const methodSubtitle = {
    authenticator: 'Enter the 6-digit code generated by your Authenticator app.',
    sms: 'We sent a 6-digit verification code via text message to +1 (•••) •••-4829.',
    email: 'We sent a 6-digit verification code to your registered email address.'
  }[method] || 'Enter your 6-digit verification code.'

  // Fetch MFA setup if using authenticator
  useEffect(() => {
    if (method === 'authenticator') {
      authService.setupMfa()
        .then((data) => {
          setQrCode(data.qr_code_url)
          setSecret(data.secret)
        })
        .catch(() => {
          toast.error('Failed to initialize MFA setup from server.')
        })
    }
  }, [method])

  // 30-second countdown timer
  useEffect(() => {
    if (timer <= 0) {
      setTimerExpired(true)
      return
    }
    const interval = setInterval(() => {
      setTimer((prev) => prev - 1)
    }, 1000)

    return () => clearInterval(interval)
  }, [timer])

  // Auto focus first input on mount
  useEffect(() => {
    if (inputRefs.current[0]) {
      inputRefs.current[0].focus()
    }
  }, [])

  const handleChange = (index: number, value: string) => {
    if (!/^\d*$/.test(value)) return // Allow only digits

    const newDigits = [...digits]
    // Take only the last character entered
    newDigits[index] = value.slice(-1)
    setDigits(newDigits)
    setError(false)

    // Automatically shift focus to next input
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus()
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace') {
      if (!digits[index] && index > 0) {
        // Shift focus to previous input if current is empty
        const newDigits = [...digits]
        newDigits[index - 1] = ''
        setDigits(newDigits)
        inputRefs.current[index - 1]?.focus()
      } else {
        // Just clear current
        const newDigits = [...digits]
        newDigits[index] = ''
        setDigits(newDigits)
      }
    }
  }

  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData('text').trim().slice(0, 6)
    if (!/^\d+$/.test(pastedData)) return // Ensure only digits

    const newDigits = [...digits]
    for (let i = 0; i < pastedData.length; i++) {
      newDigits[i] = pastedData[i]
    }
    setDigits(newDigits)
    setError(false)

    // Focus last filled or next empty
    const focusIndex = Math.min(pastedData.length, 5)
    inputRefs.current[focusIndex]?.focus()
  }

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault()
    const code = digits.join('')
    if (code.length < 6) {
      setError(true)
      toast.error('Please fill in all 6 digits.')
      return
    }

    if (timerExpired) {
      setError(true)
      toast.error('The verification code has expired. Please request a new one.')
      return
    }

    setLoading(true)
    setError(false)

    try {
      await authService.verifyMfa(code)
      toast.success('MFA verification successful!')
      
      const token = useAuthStore.getState().accessToken
      const route = token ? getDefaultRoute(getRolesFromToken(token)) : '/dashboard'
      navigate(route)
    } catch {
      setError(true)
      toast.error('Invalid verification code. Please try again.')
      setLoading(false)
    }
  }

  const handleResend = () => {
    setTimer(30)
    setTimerExpired(false)
    setDigits(Array(6).fill(''))
    setError(false)

    if (method === 'authenticator') {
      authService.setupMfa()
        .then((data) => {
          setQrCode(data.qr_code_url)
          setSecret(data.secret)
          toast.success('Generated a new Authenticator setup code.')
        })
        .catch(() => {
          toast.error('Failed to regenerate setup code.')
        })
    } else {
      toast.success('A new 6-digit passcode has been generated/sent!')
    }

    setTimeout(() => {
      if (inputRefs.current[0]) {
        inputRefs.current[0].focus()
      }
    }, 100)
  }

  const handleBackToMethods = () => {
    navigate('/mfa-select')
  }

  const handleCancel = () => {
    clearAuth()
    navigate('/login')
  }

  const digitErrorStyle = error ? { borderColor: 'var(--color-error)' } : {}

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <div style={{ textAlign: 'center', marginBottom: '0.25rem' }}>
        <h3 style={{
          fontFamily: 'var(--font-headline)',
          fontSize: '1.25rem',
          fontWeight: 700,
          color: 'var(--color-text)',
          margin: '0 0 0.5rem 0'
        }}>
          {methodTitle}
        </h3>
        <p style={{
          fontSize: '0.875rem',
          color: 'var(--color-text-muted)',
          lineHeight: '1.4',
          margin: 0
        }}>
          {methodSubtitle}
        </p>
      </div>

      {error && (
        <div style={{
          backgroundColor: 'var(--color-error-bg)',
          border: '1px solid var(--color-error)',
          color: 'var(--color-error)',
          padding: '0.75rem 1rem',
          borderRadius: '8px',
          fontSize: '0.8125rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          margin: '0 0 0.5rem 0'
        }}>
          <span className="material-symbols-outlined" style={{ fontSize: '18px', flexShrink: 0 }}>
            error
          </span>
          <div>
            <strong>Verification Error:</strong> {timerExpired ? 'The code has expired.' : 'Invalid digit passcode sequence.'}
          </div>
        </div>
      )}

      {method === 'authenticator' && qrCode && (
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: '0.75rem',
          padding: '1rem',
          backgroundColor: 'var(--color-surface-hover)',
          border: '1px dashed var(--color-border)',
          borderRadius: '8px',
          margin: '0.5rem 0'
        }}>
          <p style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)', margin: 0, textAlign: 'center' }}>
            Scan this QR code in your Authenticator app to configure MFA:
          </p>
          <img
            src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(qrCode)}`}
            alt="MFA QR Code"
            style={{ width: '150px', height: '150px', backgroundColor: '#fff', padding: '4px', borderRadius: '4px' }}
          />
          <div style={{ textAlign: 'center' }}>
            <span style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>Secret Key:</span>{' '}
            <code style={{ fontSize: '0.8125rem', fontWeight: 600, color: 'var(--color-text)', userSelect: 'all' }}>
              {secret}
            </code>
          </div>
        </div>
      )}

      <form onSubmit={handleVerify} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', gap: '0.5rem' }}>
          {digits.map((digit, index) => (
            <input
              key={index}
              ref={(el) => { inputRefs.current[index] = el }}
              type="text"
              inputMode="numeric"
              pattern="[0-9]*"
              value={digit}
              onChange={(e) => handleChange(index, e.target.value)}
              onKeyDown={(e) => handleKeyDown(index, e)}
              onPaste={index === 0 ? handlePaste : undefined}
              maxLength={1}
              style={{
                width: '44px',
                height: '48px',
                textAlign: 'center',
                fontSize: '1.5rem',
                fontWeight: 700,
                borderRadius: '8px',
                border: '1px solid var(--color-border)',
                outline: 'none',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                ...digitErrorStyle
              }}
              required
            />
          ))}
        </div>

        {/* Timer countdown indicators */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.8125rem' }}>
          <div style={{ color: 'var(--color-text-muted)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
            <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>
              schedule
            </span>
            {timerExpired ? (
              <span style={{ color: 'var(--color-error)', fontWeight: 600 }}>Code Expired</span>
            ) : (
              <span>Code expires in <strong style={{ color: 'var(--color-primary)' }}>{timer}s</strong></span>
            )}
          </div>
          {(method === 'sms' || method === 'email' || timerExpired) && (
            <button
              type="button"
              onClick={handleResend}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--color-primary)',
                fontWeight: 600,
                cursor: 'pointer',
                padding: 0
              }}
            >
              Resend Code
            </button>
          )}
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginTop: '0.25rem' }}>
          <button
            type="submit"
            className="btn btn-primary"
            style={{ 
              width: '100%', 
              padding: '0.625rem', 
              fontSize: '0.875rem', 
              fontWeight: 600, 
              display: 'flex', 
              justifyContent: 'center', 
              alignItems: 'center' 
            }}
            disabled={loading}
          >
            {loading ? 'Verifying...' : 'Verify Access'}
          </button>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '0.25rem' }}>
            <button
              type="button"
              onClick={handleBackToMethods}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--color-primary)',
                fontSize: '0.75rem',
                fontWeight: 600,
                cursor: 'pointer',
                padding: 0
              }}
            >
              ← Use different method
            </button>
            
            <button
              type="button"
              onClick={handleCancel}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--color-text-light)',
                fontSize: '0.75rem',
                fontWeight: 500,
                cursor: 'pointer',
                padding: 0
              }}
            >
              Sign out
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
